/*
Copyright 2013-present Barefoot Networks, Inc. 

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
/*
 *
 * DO NOT EDIT:  This file is automatically generated.
 *
 */

#include "rocker_p4_rmt.h"
#include "rocker_p4_l2l3_enums.h"
#include "rocker_p4_l2l3_tables.h"
#include "rocker_p4_l2l3_pd.h"

#define PD_DEBUG 1

#define HOST_BYTE_ORDER_CALLER 1

#define BYTE_ROUND_UP(x) ((x + 7) >> 3)


static inline void rocker_p4_l2l3_build_key_port_vlan_mapping
(
 unsigned char *key,
 rocker_p4_l2l3_port_vlan_mapping_match_spec_t *match_spec
)
{
#ifdef HOST_BYTE_ORDER_CALLER
  unsigned int tmp32;
  (void) tmp32;
#endif

  *(key++) = (match_spec->vlan_tag__valid > 0);

#ifdef HOST_BYTE_ORDER_CALLER
  tmp32 = match_spec->vlan_tag__vid;
  tmp32 = htonl(tmp32);
  *(unsigned int *) key = tmp32;
#else
  *(unsigned int *) key = match_spec->vlan_tag__vid;
#endif
  key += sizeof(unsigned int);
  
#ifdef HOST_BYTE_ORDER_CALLER
  tmp32 = match_spec->standard_metadata_ingress_port;
  tmp32 = htonl(tmp32);
  *(unsigned int *) key = tmp32;
#else
  *(unsigned int *) key = match_spec->standard_metadata_ingress_port;
#endif
  key += sizeof(unsigned int);
  
}

static inline void rocker_p4_l2l3_build_key_dmac
(
 unsigned char *key,
 rocker_p4_l2l3_dmac_match_spec_t *match_spec
)
{
#ifdef HOST_BYTE_ORDER_CALLER
  unsigned int tmp32;
  (void) tmp32;
#endif

#ifdef HOST_BYTE_ORDER_CALLER
  tmp32 = match_spec->ingress_metadata_fid;
  tmp32 = htonl(tmp32);
  *(unsigned int *) key = tmp32;
#else
  *(unsigned int *) key = match_spec->ingress_metadata_fid;
#endif
  key += sizeof(unsigned int);
  
  memcpy(key, match_spec->ethernet_dstAddr, 6);
  key += 6;
  
}

static inline void rocker_p4_l2l3_build_key_smac
(
 unsigned char *key,
 rocker_p4_l2l3_smac_match_spec_t *match_spec
)
{
#ifdef HOST_BYTE_ORDER_CALLER
  unsigned int tmp32;
  (void) tmp32;
#endif

#ifdef HOST_BYTE_ORDER_CALLER
  tmp32 = match_spec->ingress_metadata_fid;
  tmp32 = htonl(tmp32);
  *(unsigned int *) key = tmp32;
#else
  *(unsigned int *) key = match_spec->ingress_metadata_fid;
#endif
  key += sizeof(unsigned int);
  
  memcpy(key, match_spec->ethernet_srcAddr, 6);
  key += 6;
  
}


static inline void rocker_p4_l2l3_build_action_spec_port_vlan_hit
(
 unsigned char *data,
 rocker_p4_l2l3_port_vlan_hit_action_spec_t *action_spec
)
{
#ifdef HOST_BYTE_ORDER_CALLER
  unsigned short tmp16;
  unsigned int tmp32;
  (void) tmp16;
  (void) tmp32;
#endif

#ifdef HOST_BYTE_ORDER_CALLER
  tmp32 = action_spec->action_fid;
  tmp32 = htonl(tmp32);
  *(unsigned int *) data = tmp32;
#else
  *(unsigned int *) data = action_spec->action_fid;
#endif
  data += sizeof(unsigned int);


}

static inline void rocker_p4_l2l3_build_action_spec_dmac_hit
(
 unsigned char *data,
 rocker_p4_l2l3_dmac_hit_action_spec_t *action_spec
)
{
#ifdef HOST_BYTE_ORDER_CALLER
  unsigned short tmp16;
  unsigned int tmp32;
  (void) tmp16;
  (void) tmp32;
#endif

#ifdef HOST_BYTE_ORDER_CALLER
  tmp32 = action_spec->action_port;
  tmp32 = htonl(tmp32);
  *(unsigned int *) data = tmp32;
#else
  *(unsigned int *) data = action_spec->action_port;
#endif
  data += sizeof(unsigned int);


}


/* ADD ENTRIES */

/**
 * @brief rocker_p4_l2l3_port_vlan_mapping_table_entry_create_with_port_vlan_hit
 * @param sess_hdl
 * @param dev_tgt
 * @param match_spec
 * @param action_spec
 * @param entry_hdl
*/
rocker_p4_status_t
rocker_p4_l2l3_port_vlan_mapping_table_entry_create_with_port_vlan_hit
(
 rocker_p4_l2l3_port_vlan_mapping_match_spec_t *match_spec,
 rocker_p4_l2l3_port_vlan_hit_action_spec_t *action_spec,
 rocker_p4_l2l3_port_vlan_mapping_entry_t *entry,
 rocker_p4_entry_hdl_t *entry_hdl
)
{


  entry->action_id = 0;

  rocker_p4_l2l3_build_key_port_vlan_mapping(entry->key, match_spec);



  rocker_p4_l2l3_build_action_spec_port_vlan_hit(entry->action_data, action_spec);

  *entry_hdl = 0;
  return 0;
}

/**
 * @brief rocker_p4_l2l3_port_vlan_mapping_table_entry_create_with_port_vlan_miss
 * @param sess_hdl
 * @param dev_tgt
 * @param match_spec
 * @param entry_hdl
*/
rocker_p4_status_t
rocker_p4_l2l3_port_vlan_mapping_table_entry_create_with_port_vlan_miss
(
 rocker_p4_l2l3_port_vlan_mapping_match_spec_t *match_spec,
 rocker_p4_l2l3_port_vlan_mapping_entry_t *entry,
 rocker_p4_entry_hdl_t *entry_hdl
)
{


  entry->action_id = 1;

  rocker_p4_l2l3_build_key_port_vlan_mapping(entry->key, match_spec);




  *entry_hdl = 0;
  return 0;
}

/**
 * @brief rocker_p4_l2l3_dmac_table_entry_create_with_dmac_hit
 * @param sess_hdl
 * @param dev_tgt
 * @param match_spec
 * @param action_spec
 * @param entry_hdl
*/
rocker_p4_status_t
rocker_p4_l2l3_dmac_table_entry_create_with_dmac_hit
(
 rocker_p4_l2l3_dmac_match_spec_t *match_spec,
 rocker_p4_l2l3_dmac_hit_action_spec_t *action_spec,
 rocker_p4_l2l3_dmac_entry_t *entry,
 rocker_p4_entry_hdl_t *entry_hdl
)
{


  entry->action_id = 0;

  rocker_p4_l2l3_build_key_dmac(entry->key, match_spec);



  rocker_p4_l2l3_build_action_spec_dmac_hit(entry->action_data, action_spec);

  *entry_hdl = 0;
  return 0;
}

/**
 * @brief rocker_p4_l2l3_dmac_table_entry_create_with_dmac_miss
 * @param sess_hdl
 * @param dev_tgt
 * @param match_spec
 * @param entry_hdl
*/
rocker_p4_status_t
rocker_p4_l2l3_dmac_table_entry_create_with_dmac_miss
(
 rocker_p4_l2l3_dmac_match_spec_t *match_spec,
 rocker_p4_l2l3_dmac_entry_t *entry,
 rocker_p4_entry_hdl_t *entry_hdl
)
{


  entry->action_id = 1;

  rocker_p4_l2l3_build_key_dmac(entry->key, match_spec);




  *entry_hdl = 0;
  return 0;
}

/**
 * @brief rocker_p4_l2l3_smac_table_entry_create_with_smac_hit
 * @param sess_hdl
 * @param dev_tgt
 * @param match_spec
 * @param entry_hdl
*/
rocker_p4_status_t
rocker_p4_l2l3_smac_table_entry_create_with_smac_hit
(
 rocker_p4_l2l3_smac_match_spec_t *match_spec,
 rocker_p4_l2l3_smac_entry_t *entry,
 rocker_p4_entry_hdl_t *entry_hdl
)
{


  entry->action_id = 0;

  rocker_p4_l2l3_build_key_smac(entry->key, match_spec);




  *entry_hdl = 0;
  return 0;
}

/**
 * @brief rocker_p4_l2l3_smac_table_entry_create_with_smac_miss
 * @param sess_hdl
 * @param dev_tgt
 * @param match_spec
 * @param entry_hdl
*/
rocker_p4_status_t
rocker_p4_l2l3_smac_table_entry_create_with_smac_miss
(
 rocker_p4_l2l3_smac_match_spec_t *match_spec,
 rocker_p4_l2l3_smac_entry_t *entry,
 rocker_p4_entry_hdl_t *entry_hdl
)
{


  entry->action_id = 1;

  rocker_p4_l2l3_build_key_smac(entry->key, match_spec);




  *entry_hdl = 0;
  return 0;
}


/* SET DEFAULT_ACTION */

/**
 * @brief rocker_p4_l2l3_port_vlan_mapping_set_default_action_port_vlan_hit
 * @param action_spec
*/
unsigned int
rocker_p4_l2l3_port_vlan_mapping_set_default_action_port_vlan_hit
(
 rocker_p4_l2l3_port_vlan_hit_action_spec_t *action_spec
)
{
  unsigned char _data[4];
  rocker_p4_l2l3_build_action_spec_port_vlan_hit(_data, action_spec);

  return 0;
}

/**
 * @brief rocker_p4_l2l3_port_vlan_mapping_set_default_action_port_vlan_miss
*/
unsigned int
rocker_p4_l2l3_port_vlan_mapping_set_default_action_port_vlan_miss
(
 void
)
{

  return 1;
}

/**
 * @brief rocker_p4_l2l3_dmac_set_default_action_dmac_hit
 * @param action_spec
*/
unsigned int
rocker_p4_l2l3_dmac_set_default_action_dmac_hit
(
 rocker_p4_l2l3_dmac_hit_action_spec_t *action_spec
)
{
  unsigned char _data[4];
  rocker_p4_l2l3_build_action_spec_dmac_hit(_data, action_spec);

  return 0;
}

/**
 * @brief rocker_p4_l2l3_dmac_set_default_action_dmac_miss
*/
unsigned int
rocker_p4_l2l3_dmac_set_default_action_dmac_miss
(
 void
)
{

  return 1;
}

/**
 * @brief rocker_p4_l2l3_smac_set_default_action_smac_hit
*/
unsigned int
rocker_p4_l2l3_smac_set_default_action_smac_hit
(
 void
)
{

  return 0;
}

/**
 * @brief rocker_p4_l2l3_smac_set_default_action_smac_miss
*/
unsigned int
rocker_p4_l2l3_smac_set_default_action_smac_miss
(
 void
)
{

  return 1;
}



/* INDIRECT ACTION DATA AND MATCH SELECT */




