/*
Copyright 2013-present Barefoot Networks, Inc. 

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
/*
 * DO NOT EDIT:  This file is automatically generated.
 *
 */

#ifndef _ROCKER_p4_l2l3PD_H
#define _ROCKER_p4_l2l3PD_H

typedef unsigned int rocker_p4_status_t;
typedef unsigned int rocker_p4_entry_hdl_t;



/* MATCH STRUCTS */

typedef struct rocker_p4_l2l3_port_vlan_mapping_match_spec {
  unsigned char vlan_tag__valid;
  unsigned short vlan_tag__vid;
  unsigned short standard_metadata_ingress_port;
} rocker_p4_l2l3_port_vlan_mapping_match_spec_t;

typedef struct rocker_p4_l2l3_dmac_match_spec {
  unsigned short ingress_metadata_fid;
  unsigned char ethernet_dstAddr[6];
} rocker_p4_l2l3_dmac_match_spec_t;

typedef struct rocker_p4_l2l3_smac_match_spec {
  unsigned short ingress_metadata_fid;
  unsigned char ethernet_srcAddr[6];
} rocker_p4_l2l3_smac_match_spec_t;



/* ACTION STRUCTS */

/* dmac_miss has no parameters */

/* smac_hit has no parameters */

typedef struct rocker_p4_l2l3_port_vlan_hit_action_spec {
  unsigned int action_fid;
} rocker_p4_l2l3_port_vlan_hit_action_spec_t;

/* smac_miss has no parameters */

/* port_vlan_miss has no parameters */

typedef struct rocker_p4_l2l3_dmac_hit_action_spec {
  unsigned int action_port;
} rocker_p4_l2l3_dmac_hit_action_spec_t;



/* ADD ENTRIES */

/**
 * @brief rocker_p4_l2l3_port_vlan_mapping_table_entry_create_with_port_vlan_hit
 * @param match_spec
 * @param action_spec
 * @param entry_hdl
*/
rocker_p4_status_t
rocker_p4_l2l3_port_vlan_mapping_table_entry_create_with_port_vlan_hit
(
 rocker_p4_l2l3_port_vlan_mapping_match_spec_t *match_spec,
 rocker_p4_l2l3_port_vlan_hit_action_spec_t *action_spec,
 rocker_p4_l2l3_port_vlan_mapping_entry_t *entry,
 rocker_p4_entry_hdl_t *entry_hdl
);

/**
 * @brief rocker_p4_l2l3_port_vlan_mapping_table_entry_create_with_port_vlan_miss
 * @param match_spec
 * @param entry_hdl
*/
rocker_p4_status_t
rocker_p4_l2l3_port_vlan_mapping_table_entry_create_with_port_vlan_miss
(
 rocker_p4_l2l3_port_vlan_mapping_match_spec_t *match_spec,
 rocker_p4_l2l3_port_vlan_mapping_entry_t *entry,
 rocker_p4_entry_hdl_t *entry_hdl
);

/**
 * @brief rocker_p4_l2l3_dmac_table_entry_create_with_dmac_hit
 * @param match_spec
 * @param action_spec
 * @param entry_hdl
*/
rocker_p4_status_t
rocker_p4_l2l3_dmac_table_entry_create_with_dmac_hit
(
 rocker_p4_l2l3_dmac_match_spec_t *match_spec,
 rocker_p4_l2l3_dmac_hit_action_spec_t *action_spec,
 rocker_p4_l2l3_dmac_entry_t *entry,
 rocker_p4_entry_hdl_t *entry_hdl
);

/**
 * @brief rocker_p4_l2l3_dmac_table_entry_create_with_dmac_miss
 * @param match_spec
 * @param entry_hdl
*/
rocker_p4_status_t
rocker_p4_l2l3_dmac_table_entry_create_with_dmac_miss
(
 rocker_p4_l2l3_dmac_match_spec_t *match_spec,
 rocker_p4_l2l3_dmac_entry_t *entry,
 rocker_p4_entry_hdl_t *entry_hdl
);

/**
 * @brief rocker_p4_l2l3_smac_table_entry_create_with_smac_hit
 * @param match_spec
 * @param entry_hdl
*/
rocker_p4_status_t
rocker_p4_l2l3_smac_table_entry_create_with_smac_hit
(
 rocker_p4_l2l3_smac_match_spec_t *match_spec,
 rocker_p4_l2l3_smac_entry_t *entry,
 rocker_p4_entry_hdl_t *entry_hdl
);

/**
 * @brief rocker_p4_l2l3_smac_table_entry_create_with_smac_miss
 * @param match_spec
 * @param entry_hdl
*/
rocker_p4_status_t
rocker_p4_l2l3_smac_table_entry_create_with_smac_miss
(
 rocker_p4_l2l3_smac_match_spec_t *match_spec,
 rocker_p4_l2l3_smac_entry_t *entry,
 rocker_p4_entry_hdl_t *entry_hdl
);


/* SET DEFAULT_ACTION */

/**
 * @brief rocker_p4_l2l3_port_vlan_mapping_set_default_action_port_vlan_hit
 * @param action_spec
*/
unsigned int
rocker_p4_l2l3_port_vlan_mapping_set_default_action_port_vlan_hit
(
 rocker_p4_l2l3_port_vlan_hit_action_spec_t *action_spec
);

/**
 * @brief rocker_p4_l2l3_port_vlan_mapping_set_default_action_port_vlan_miss
*/
unsigned int
rocker_p4_l2l3_port_vlan_mapping_set_default_action_port_vlan_miss
(
 void
);

/**
 * @brief rocker_p4_l2l3_dmac_set_default_action_dmac_hit
 * @param action_spec
*/
unsigned int
rocker_p4_l2l3_dmac_set_default_action_dmac_hit
(
 rocker_p4_l2l3_dmac_hit_action_spec_t *action_spec
);

/**
 * @brief rocker_p4_l2l3_dmac_set_default_action_dmac_miss
*/
unsigned int
rocker_p4_l2l3_dmac_set_default_action_dmac_miss
(
 void
);

/**
 * @brief rocker_p4_l2l3_smac_set_default_action_smac_hit
*/
unsigned int
rocker_p4_l2l3_smac_set_default_action_smac_hit
(
 void
);

/**
 * @brief rocker_p4_l2l3_smac_set_default_action_smac_miss
*/
unsigned int
rocker_p4_l2l3_smac_set_default_action_smac_miss
(
 void
);




#endif
